### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by kaustubhcs** [alihassanijr/FancySMI#1]
Installed rich using pip3
```
$> pip3 install rich
Requirement already satisfied: rich in /lib/python3.8/site-packages (12.5.1)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /lib/python3.8/site-packages (from rich) (4.3.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /python3.8/site-packages (from rich) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /lib/python3.8/site-packages (from rich) (2.10.0)
```
```
$> ./fancy-smi
Traceback (most recent call last):
  File "./fancy-smi", line 12, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
```

**Comment by alihassanijr** [comment]
Thanks for sharing this.
I think it's probably because it's calling a different python install, this has happened to me once before but I can't reproduce it.
Could you do a `which python3` and then change 
https://github.com/alihassanijr/FancySMI/blob/413daa5393718c655b75767089fc7b67ae81b9d6/fancy-smi#L1
to that path?

I'm going to try and figure out a solution to this.

**Comment by kaustubhcs** [comment]
That was the issue :D
It worked!
![image](https://user-images.githubusercontent.com/7969023/194148349-c6244ab2-08cd-4c95-8ff3-adb2b587547c.png)
